/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'hoymiles-wifi adapter settings': {
        'en': 'Adapter settings for hoymiles-wifi',
        'de': 'Adaptereinstellungen für hoymiles-wifi',
        'ru': 'Настройки адаптера для hoymiles-wifi',
        'pt': 'Configurações do adaptador para hoymiles-wifi',
        'nl': 'Adapterinstellingen voor hoymiles-wifi',
        'fr': "Paramètres d'adaptateur pour hoymiles-wifi",
        'it': "Impostazioni dell'adattatore per hoymiles-wifi",
        'es': 'Ajustes del adaptador para hoymiles-wifi',
        'pl': 'Ustawienia adaptera dla hoymiles-wifi',
        'zh-cn': 'hoymiles-wifi的适配器设置'
    },
    'host': {
	  "en": "host (IP address of Hoymiles HMS):",
	  "de": "Host (IP-Adresse der Hoymiles HMS):",
	  "ru": "хост (IP-адрес HMS Hoymiles):",
	  "pt": "host (endereço IP de Hoymiles HMS):",
	  "nl": "host (IP-adres van Hoymiles HMS):",
	  "fr": "hôte (adresse IP de Hoymiles HMS):",
	  "it": "host (indirizzo IP di Hoymiles HMS):",
	  "es": "host (dirección IP de Hoymiles HMS):",
	  "pl": "host (adres IP Hoymiles HMS):",
	  "uk": "хост (IP-адреса Hoymiles HMS):",
	  "zh-cn": "主机(Hoymiles HMS的IP地址):"
    },
    'pull Option': {
        "en": "Pause pulling data at night?",
        "de": "Datenbezug nachts pausieren?",
        "ru": "Данные опроса о паузе ночью?",
        "pt": "Pausa dados de sondagem à noite?",
        "nl": "Gegevens pauzeren 's nachts?",
        "fr": "Arrêter les données de vote la nuit ?",
        "it": "Pausa inquinare i dati di notte?",
        "es": "¿Pausa los datos de las encuestas por la noche?",
        "pl": "Wstrzymać sondaże w nocy?",
        "uk": "Опитування даних за ніч?",
        "zh-cn": "晚上暂停投票?"
    },
    'skippulling': {
        "en": "DELETE Skip updating (while device not reachable by PING)",
        "de": "Aktualisierung überspringen (wenn das Gerät nicht durch PING erreichbar ist)",
        "ru": "Обновление скипа (в то время как устройство недоступно PING)",
        "pt": "Pular atualização (enquanto dispositivo não acessível por PING)",
        "nl": "Bijwerken overslaan (terwijl apparaat niet bereikbaar door PING)",
        "fr": "Sauter la mise à jour (alors que l'appareil n'est pas accessible par PING)",
        "it": "Salta l'aggiornamento (mentre il dispositivo non raggiungibile da PING)",
        "es": "Saltar actualización (mientras dispositivo no accesible por PING)",
        "pl": "Pomiń aktualizację (podczas gdy urządzenie nie jest osiągalne przez PING)",
        "uk": "Оновлення пропуску (пристрій не досягається PING)",
        "zh-cn": "跳过更新( 而 PING 无法到达的设备)"
    },
    'Ask always, even at night when device is unreachable': {
        "en": "Ask always, even at night when device is unreachable",
        "de": "Abfragen immer, auch nachts, wenn das Gerät nicht erreichbar ist",
        "ru": "Спросите всегда, даже ночью, когда устройство недоступно",
        "pt": "Pergunte sempre, mesmo à noite quando o dispositivo é inacessível",
        "nl": "Vraag altijd, zelfs 's nachts wanneer het apparaat onbereikbaar is",
        "fr": "Demandez toujours, même la nuit quand l'appareil est inaccessible",
        "it": "Chiedi sempre, anche di notte quando il dispositivo è irraggiungibile",
        "es": "Pregunta siempre, incluso por la noche cuando el dispositivo es inalcanzable",
        "pl": "Pytaj zawsze, nawet w nocy, gdy urządzenie jest nieosiągalne",
        "uk": "Запитайте завжди, навіть вночі, коли пристрій ненадійне",
        "zh-cn": "总是问,即使晚上设备无法到达"
    },
    'Ask only at day, when device is reached by system command PING': {
        "en": "Ask only at day, when device is reached by system command PING",
        "de": "Abfragen nur am Tag, wenn das Gerät durch den Systembefehl PING erreicht wird",
        "ru": "Спросить только в день, когда устройство достигается по системной команде PING",
        "pt": "Pergunte apenas no dia, quando o dispositivo é alcançado pelo comando do sistema PING",
        "nl": "Vraag alleen op dag, wanneer het apparaat is bereikt door systeemopdracht PING",
        "fr": "Demandez seulement au jour, quand l'appareil est atteint par la commande système PING",
        "it": "Chiedere solo al giorno, quando il dispositivo è raggiunto dal comando di sistema PING",
        "es": "Pregunte sólo al día, cuando el dispositivo es alcanzado por el comando del sistema PING",
        "pl": "Pytaj tylko w dzień, gdy urządzenie jest osiągane przez polecenie systemowe",
        "uk": "Запитайте лише в день, коли пристрій досягається за допомогою системи PING",
        "zh-cn": "仅在系统命令 PING 到达设备的当天询问"
    },
    'Ask only at day, when object is positive reachable by separate iobroker adapter PING': {
        "en": "Ask only at day, when object is positive reachable by separate iobroker adapter PING",
        "de": "Abfragen nur am Tag, wenn das Objekt durch separaten ioBrokeradapter PING positiv erreichbar ist",
        "ru": "Спроси только в день, когда объект положительно достижим отдельным адаптером iobroker PING",
        "pt": "Pergunte apenas no dia, quando o objeto é atingível positivo pelo adaptador separado do iobroker PING",
        "nl": "Vraag het alleen overdag, als object positief bereikbaar is door afzonderlijke iobroker adapter PING",
        "fr": "Demandez seulement au jour, lorsque l'objet est accessible positivement par adaptateur iobroker séparé PING",
        "it": "Chiedere solo al giorno, quando l'oggetto è positivo raggiungibile da adattatore iobroker separato PING",
        "es": "Pregunte sólo al día, cuando el objeto es positivo alcanzable por separado iobroker adaptador PING",
        "pl": "Pytaj tylko w dzień, gdy obiekt jest pozytywny osiągalny przez oddzielny adapter iobroker PING",
        "uk": "Запитайте тільки в день, коли об'єкт позитивно досягається від окремого адаптера iobroker PING",
        "zh-cn": "仅在日内询问, 当对象通过单独的 iobrocast 适配器 PING 实现时"
    },
    'For option 3 - string to object of MHS in PING adapter': {
        "en": "For option 3 - string to object of MHS in PING adapter (reach with key TAB)",
        "de": "Für Option 3 - String zum Objekt von MHS in PING Adapter (erreichbar per TAB)",
        "ru": "Для варианта 3 - строка к объекту MHS в адаптере PING (приближается с ключом TAB)",
        "pt": "Para a opção 3 - string para objeto de MHS no adaptador PING (consulte com TAB chave)",
        "nl": "Voor optie 3 - tekenreeks om MHS in PING-adapter te objecteren (bereik met sleutel TAB)",
        "fr": "Pour l'option 3 - chaîne à objet de MHS dans l'adaptateur PING (accès avec clé TAB)",
        "it": "Per opzione 3 - stringa a oggetto di MHS nell'adattatore PING (accesso con chiave TAB)",
        "es": "Para la opción 3 - string to object of MHS in PING adapter (reach with key TAB)",
        "pl": "Dla opcji 3 - ciąg znaków do obiektu MHS w adapterze WINGS (sięgać klawiszem TAB)",
        "uk": "Для параметра 3 - рядок для об'єкта MHS в адаптері PING (повіді з ключем TAB)",
        "zh-cn": "选项 3 - PING 适配器中 MHS 对象的字符串( 使用密钥 TAB 访问)"
    },
    'Command Line': {
        "en": "Command line (host and option will be replaced, please do not change this line):",
        "de": "Befehlszeile (Host und Option werden ersetzt, bitte ändern Sie diese Zeile nicht):",
        "ru": "Командная линия (хостинг и опция будут заменены, пожалуйста, не меняйте эту строку):",
        "pt": "Linha de comando (host e opção serão substituídas, por favor não altere esta linha):",
        "nl": "Opdrachtregel (host en optie worden vervangen, wijzig deze regel niet):",
        "fr": "Ligne de commande (l'hôte et l'option seront remplacés, veuillez ne pas modifier cette ligne):",
        "it": "Linea di comando (host e opzione saranno sostituiti, si prega di non cambiare questa linea):",
        "es": "Línea de comandos (host y opción será reemplazada, por favor no cambie esta línea):",
        "pl": "Linia poleceń (host i opcja zostaną zastąpione, proszę nie zmieniać tej linii):",
        "uk": "Командна лінія (приблизно і опція буде замінена, будь ласка, не змініть цей рядок):",
        "zh-cn": "命令行( 主机和选项将被替换, 请不要更改此行 ) :"
    },
    'Option1': {
        'en': 'option 1',
        'de': 'Option 1',
        'ru': 'Опция 1',
        'pt': 'Opção 1',
        'nl': 'Optie 1',
        'fr': 'Option 1',
        'it': 'opzione 1',
        'es': 'Opción 1',
        'pl': 'opcja 1',
        'zh-cn': '选项1'
    },
    'Option2': {
        'en': 'option 2',
        'de': 'Option 2',
        'ru': 'вариант 2',
        'pt': 'opção 2',
        'nl': 'Optie 2',
        'fr': 'Option 2',
        'it': 'opzione 2',
        'es': 'opcion 2',
        'pl': 'Opcja 2',
        'zh-cn': '选项2'
    },
    'Option3': {
        'en': 'option 3',
        'de': 'Option 3',
        'ru': 'Опция 3',
        'pt': 'Opção 3',
        'nl': 'Optie 3',
        'fr': 'Option 3',
        'it': 'opzione 3',
        'es': 'Opción 3',
        'pl': 'opcja 3',
        'zh-cn': '选项3'
    },
    'Option4': {
        'en': 'option 4',
        'de': 'Option 4',
        'ru': 'вариант 4',
        'pt': 'opção 4',
        'nl': 'Optie 4',
        'fr': 'Option 4',
        'it': 'opzione 4',
        'es': 'opcion 4',
        'pl': 'Opcja 4',
        'zh-cn': '选项4'
    },
    'Option5': {
        'en': 'option 5',
        'de': 'Option 5',
        'ru': 'Опция 5',
        'pt': 'Opção 5',
        'nl': 'Optie 5',
        'fr': 'Option 5',
        'it': 'opzione 5',
        'es': 'Opción 5',
        'pl': 'opcja 5',
        'zh-cn': '选项5'
    },
    'pullInterval': {
        "en": "Interval for updating values (in seconds)",
        "de": "Intervall zur Aktualisierung von Werten (in Sekunden)",
        "ru": "Интервал для обновления значений (в секундах)",
        "pt": "Intervalo para atualização de valores (em segundos)",
        "nl": "Interval voor het bijwerken van waarden (in seconden)",
        "fr": "Intervalle de mise à jour des valeurs (en secondes)",
        "it": "Intervallo per l'aggiornamento dei valori (in secondi)",
        "es": "Intervalo para actualizar valores (en segundos)",
        "pl": "Interval dla aktualizacji wartości (w sekundach)",
        "uk": "Інтервал для оновлення значень (в секундах)",
        "zh-cn": "更新值的间隔( 秒)"
    },
    'debugModeEnabled': {
        "en": "debug mode",
        "de": "debug-modus",
        "ru": "режим отладки",
        "pt": "modo de depuração",
        "nl": "debugmodus",
        "fr": "mode débogage",
        "it": "modalità debug",
        "es": "modo de depuración",
        "pl": "tryb debugowania",
        "uk": "режим відключення",
        "zh-cn": "调试模式"
    }
};